services:
  zmk-build:
    build:
      context: ..
      dockerfile: local-build/Dockerfile
    volumes:
      - ..:/workspace
      - zmk-build-cache:/root/.cache
    environment:
      - ZEPHYR_TOOLCHAIN_VARIANT=zephyr
      - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
      - ZMK_CONFIG=/workspace/config
    command: /bin/bash

volumes:
  zmk-build-cache: 